trigger:
- master

pr:
- master

resources:
  repositories:
  - repository: azure_template
    type: github
    name: mdolab/.github
    endpoint: mdolab

extends:
  template: azure/azure_template.yaml@azure_template
  parameters:
    REPO_NAME: adflow
    IGNORE_STYLE: true
    COMPLEX: true
    GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN.mk
    INTEL_CONFIG: config/defaults/config.LINUX_INTEL.mk
    BUILD_REAL: .github/build_real.sh
    TEST_REAL: .github/test_real.sh
    BUILD_COMPLEX: .github/build_complex.sh
    TEST_COMPLEX: .github/test_complex.sh