resources:
  repositories:
  - repository: azure_template
    type: github
    name: mdolab/.github
    endpoint: mdolab

pool:
    vmImage: 'ubuntu-latest'

extends:
  template: azure/azure_template.yaml@azure_template
  parameters:
    REPO_NAME: adflow
    COMPLEX: true
    GCC_CONFIG: config/defaults/config.LINUX_GFORTRAN.mk
    INTEL_CONFIG: config/defaults/config.LINUX_INTEL.mk
    INPUT_FILES: true
    STEPS_MAKE_REAL: make
    STEPS_INSTALL_REAL: pip install .
    STEPS_TEST_REAL: testflo -v .
    STEPS_MAKE_COMPLEX: make -f Makefile_CS PETSC_ARCH=complex-opt-\$COMPILERS-\$PETSCVERSION
    STEPS_INSTALL_COMPLEX: pip install .
    STEPS_TEST_COMPLEX: testflo . -m "cmplx_test*"
